In [5]:
# List 로 ndarray 만들기 : np.array()
import numpy as np
a = np.array([1,2,3,4])   # List : item 들이 콤마로 구분되어있음
print(a)
data = [1,3,5,7,9]
b = np.array(data)      # 1차원 array 생성. ndarray type 객체
print(type(data))
print(type(b))
print(b.shape)
print(b)

[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
(5,)
[1 3 5 7 9]


In [6]:
# ndarray로 2d array 생성
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0])
print(b[1])
print(b[0,0])
print(b[1,2])
print(b)

(2, 3)
[1 2 3]
[4 5 6]
1
6
[[1 2 3]
 [4 5 6]]


In [7]:
# Array 생성하는 여러가지 방법
import numpy as np
a = np.zeros((2,2))     # 2x2 행렬 filled with zeros
print(a)
b = np.ones((1,2))      # 1x2 행렬 filled with ones
print(b)
c = np.full((2,2),7)    # np.full((a,b),c)
# constant array(a x b) filled with c
print(c)
d = np.eye(2)           # np.eye(n) : nxn identity matrix 만들기
print(d)
e = np.random.random((2,2)) #Create array filled with random values (0~1사이)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.51719915 0.26655689]
 [0.91821837 0.04039425]]


In [9]:
# numpy.arange (start =0, stop, step=1, dtype)
# start (optional, default=0), stop(stop전까지(포함x)), step(optional, default=1)
# dtype(optional, default : 입력하는 값의 data type)
import numpy as np
print(np.arange(3.0))    #default dtype : float
print(np.arange(3,7))
print(np.arange(3,7,2))

[0. 1. 2.]
[3 4 5 6]
[3 5]


In [11]:
# linspace(start, stop, num = 50, endpoint = True, dtype)
# num (optional, default = 50), endpoint (optional, stop값을 output에 포함시킬지)
# dtype (optional, default = float)
# [start~stop] 구간내에 num개 균일한 간격의 값을 가지는 array생성
y = np.linspace(5,10)   # [5~10], 50 points, 10(end) included, dtype = float
print(y)
z = np.linspace(2,3,5)   #[2~3], 5 points, 3 (end) included, dtype = float
print(z)

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]
[2.   2.25 2.5  2.75 3.  ]


In [16]:
test_array = np.linspace(start = 1, stop = 5, num=4, endpoint = False)
print(test_array)
test_array2 = np.linspace(start=1, stop=5, num=4, endpoint = False, dtype = int)
print(test_array2)

[1. 2. 3. 4.]
[1 2 3 4]


In [17]:
#  difference between arange(), linspace()
import numpy as np
a = np.arange(1,2,0.1)
b = np.linspace(1,2,11)  #endpoint = 2 included
print(a)
print(b)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]


In [23]:
# NumPy Library
import numpy as np
print(np.sqrt(2))     #제곱근 : np.sqrt()
print(np.pi)          # 파이 : np.pi
print(np.sin(0))      # sin함수: np.sin()
print(np.cos(np.pi))   # cos 함수 : np.cos()
a = np.random.rand(5)  # 0과 1사이의 n개의 uniform distribution 값을 return
# np.random.random((2,2))와 다르다... (이건 random value ndarray 만드는 것)
print(a)
print(type(a))


1.4142135623730951
3.141592653589793
0.0
-1.0
[0.80533516 0.5546494  0.02728735 0.92888261 0.66763466]
<class 'numpy.ndarray'>


In [27]:
# numpy.random.choice(a, size = None, replace = True, p = None)
# 모집단으로부터 임의 sampling
# a 값이 주어지면 np.arange(a) 결과와 동일한 모집단 array가 생성
# size : sample size
# replace : True(중복 추출 가능), False (비복원 추출)
# p = 각 entry가 선택될 확률값을 나타내는 1d array. if None : 균일 확률
import numpy as np
print(np.random.choice(6,10))
# [0,1,2,3,4,5] 모집단에서 10개의 균등확률표본, 복원 추출

print(np.random.choice(10,6, replace = False))
#[0,1,2,3,..., 9] 에서 6개의 균등확률 표본, 비복원추출

#if 모집단 원소 갯수보다 많은 수의 샘플을 비복원 추출하면(replace = False) : ValueError
# 중복되지 않은 샘플 갯수를 뽑아야하는데 원소 갯수보다 크면 불가...

[3 3 0 5 4 3 5 5 3 0]
[1 9 0 6 7 2]


In [32]:
# np.random.choice()함수에서 확률 p값을 주기
import numpy as np
print(np.random.choice(6,10, p = [0.1,0.2, 0.3, 0.2, 0.1, 0.1]))
# p 가 하나의 표본 데이터 내에서의 선택확률을 의미하지는 않다...

# 1. 모집단 (a)의 원소갯수와 p의 원소갯수가 다르면 ValueError
# 2. p 원소의 전체합이 1이 아닌 경우 ValueError
# 3. p는 확률값이기 때문에 p의 원소값이 0과 1사이가 아니면 ValueError

[0 0 2 1 3 5 1 4 3 5]


In [46]:
import numpy as np
# can also randomly sample from 1-d array-like objects
fruits = ['apple', 'banana', 'cherries', 'durian', 'grapes', 'lemon','mango']
p = [0.1, 0, 0.2, 0.5, 0.1, 0.05, 0.05]
fruit_choice = np.random.choice(fruits, 3, p=p, replace=False)
print(fruit_choice)

['durian' 'grapes' 'cherries']


In [49]:
# Numpy Array 연산
# Using List, for
data = [1,2,3]
a = []
for i in data:
    a.append(2*i)
print(a)
# Using Numpy Array, Vector function
data = [1,2,3]
a = np.array(data)
a = 2*a
print(a)

[2, 4, 6]
[2 4 6]


In [50]:
# numpy array 에 값을 한번에 더하기
import numpy as np
a = np.zeros(10) + 5   #zeros() 는 dtype=float로 생성한다.
print(a)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [51]:
# numpy array에 함수 적용
import numpy as np
a = np.linspace(1,2,11)
print(np.sqrt(a))

[1.         1.04880885 1.09544512 1.14017543 1.18321596 1.22474487
 1.26491106 1.30384048 1.34164079 1.37840488 1.41421356]


In [53]:
# numpy array 산술/논리 연산
a = np.array([1,2,3])
b = np.array([10,20,30])
print(2*a + b)

print(a==2)    # 논리연산을 할 때에는 array의 각 원소들에 대한 모든 논리 비교 후 array로 return
print(b>0)
print((a==2)&(b>10))

[12 24 36]
[False  True False]
[ True  True  True]
[False  True False]


In [55]:
# numpy array 간의 연산 수행
a = np.array([1,2,3])
b = np.array([4,5,6])
#각 원소끼리 연산을 수행함
c = np.add(a,b)
print(c)
d = np.subtract(a,b)
print(d)
e = np.multiply(a,b)
print(e)
f = np.divide(a,b)
print(f)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [57]:
a = np.array([[1,2],[3,4]])
s = np.sum(a)    #np.sum() : array의 모든 원소들을 합함.
print(s)
# np.sum()에 axis=0 or 1 선택 옵션을 추가할 수 있는데, axis ==0 : 열끼리 연산, axis==1 : 행끼리 연산
# axis (default= None) : 모든 element에 대해 연산 (값 return)
s = np.sum(a, axis=0)
print(s)
s = np.sum(a, axis=1)
print(s)
s = np.prod(a)     # np.prod() : array 의 요소들끼리 곱하는 것. axis 옵션은 sum때와 동일
print(s)

10
[4 6]
[3 7]
24


In [58]:
# numpy array의 indexing, slicing
import numpy as np
a = np.array([1,2,3,4])
print(a[1], a[-1])
print(a[1:])

2 4
[2 3 4]


In [66]:
import numpy as np
# slicing
data = [
    [1,2,3,4,5],
    [5,6,7,8,10],
    [11,12,13,14,15]
]
a = np.array(data)
s1 = a[ 0:2, 0:3 ]    #0,1행 , 0,1,2 열
print(s1)

s2 = a[1:, 0:]    # 1~행, 모든 열
print(s2)

s3 = a[1:, 3:]    # 1,2행, 3,4열
print(s3)

[[1 2 3]
 [5 6 7]]
[[ 5  6  7  8 10]
 [11 12 13 14 15]]
[[ 8 10]
 [14 15]]


In [67]:
a = np.array(data)
s = a[[0,2], [1,4]]     #인덱스로 구성된 sub-array 구성
# a[[row index list], [column index list]]
# s = [[0,1], [2,4]]
print(s)

[ 2 15]


In [68]:
# Boolean indexing!!
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]
a = np.array(data)
bool_i = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])
b = a[bool_i]   #boolean array값에 따라 masking!!
print(b)

[2 4 6 8]


In [70]:
#Filtering array
data = [[1,2,3],
        [4,5,6],
        [7,8,9]
       ]
a = np.array(data)
bool_i = (a%2==0)        # array a 에 대해 원소가 짝수이면 True, else:False
print("***boolean indexing array : bool_i ***")
print(bool_i)
print("*** 짝수만 선택 ***")
print(a[bool_i])        # Masking
print('\n')

#Simpler Way
b = a[a%2==0]
print("*** 짝수만 선택 v2 ***")
print(b)

***boolean indexing array : bool_i ***
[[False  True False]
 [ True False  True]
 [False  True False]]
*** 짝수만 선택 ***
[2 4 6 8]


*** 짝수만 선택 v2 ***
[2 4 6 8]
